### PR TITLE
Feat/container mfa

### PR DESCRIPTION
**Pull request by frenautvh**
| Question         | Answer
| ---------------- | ---
| Branch?          | feat/container-mfa
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-10083
| License          | BSD 3-Clause

## Description

move mfa-enrollment to container

### CODE REVIEW

**Review by cbourgois — APPROVED** [review]

**Review by Jisay — DISMISSED** [review]

**Comment by frenautvh** [comment]
rebased on develop b9db1c779e8d4df98d70f83bf89d9f124a4c5b4f

**Review by cbourgois — APPROVED** [review]

**Comment by frenautvh** [comment]
rebased on release/core-stack-w41

**Review by antleblanc — CHANGES_REQUESTED** [review]
Rebase required.

**Comment by frenautvh** [comment]
rebased on master 41061315d5b7afea40b36c2b0aade721ae7eeb8b

**Comment by frenautvh** [comment]
rebased on master 856ab327620e10932e01f4a5a131e8ba74a4e7be

**Comment by frenautvh** [comment]
rebased on master f183ccf693b159d2f340eaa0e74dc7d90ba8fa40

**Review by cbourgois — APPROVED** [review]

**Pull request merged**
