### PR TITLE
fix: add missing account and notifications sidebar components 

### PR DESCRIPTION
**Pull request by frenautvh**
Signed-off-by: frenauvh <florian.renaut@corp.ovh.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-17744
| License          | BSD 3-Clause

## Description

add missing side panels to cloud app

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report test-manager_2#14226.0 ✘  
* Stage 1
  * e2e -   
  * lint ✔ 
  * SemVer ✘

**Comment by antleblanc** [comment]
@frenautvh Could you please target `master` branch?

In order to be able to put it in production as quickly as possible.

Thank you!

**Comment by antleblanc** [comment]
Rebasing

**Comment by antleblanc** [comment]
Rebased on `master` branch.

**Pull request merged**
