### PR TITLE
Import @ovh-ux/ng-ovh-toaster

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-4524
| License          | BSD 3-Clause

## Description

Import **@ovh-ux/ng-ovh-toaster** :truck:

Using following command:

```sh
lerna import ~/Code/github/ovh-ux/ng-ovh-toaster \
  --dest=packages/components \
  --preserve-commit
```

### :construction_worker_man: Build

0d4650a - build: remove extra parts

### :memo: Documentation

adb4ce6 - docs: update README.md file

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#10646.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#10646.0 ✘  
* 
  * Build ✘

**Comment by antleblanc** [comment]
`yarn.lock` conflict solved via following commit: 5e3b322

**Comment by ovh-cds** [comment]
CDS Report installation#10789.0 ✘  
* Stage 1
  * Install ✘

**Comment by ovh-cds** [comment]
CDS Report installation#10789.0 ✘  
* Stage 1
  * Install ✘

**Pull request merged**
