### PR TITLE
Feat/support

### PR DESCRIPTION
**Pull request by FredericEspiau**
# :card_index: Disclaimer

This PR was already PR validated

# :house: Internal reference

MANAGER-2803

# Participants
- @frenautvh  (sorry your name might disappear when I'll redo the history 😅 )
- @FredericEspiau 

Everyone who code reviewed, prodded, merged and tutti quanti

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report deploy_uxci_ca#6516.0 ✘  
* deploy_uxci
  * deploy_uxci ✘

**Comment by ovh-cds** [comment]
CDS Report deploy_uxci_us#6516.0 ✘  
* deploy_uxci
  * deploy_uxci ✘

**Comment by marie-j** [comment]
@FredericEspiau you have conflicts

**Comment by FredericEspiau** [comment]
@marie-j thanks, I guess they arrived this morning

**Comment by ovh-cds** [comment]
CDS Report deploy_uxci_ca#6572.0 ✘  
* deploy_uxci
  * deploy_uxci ✘

**Pull request merged**
