### PR TITLE
Fix/solarsteein

### PR DESCRIPTION
**Pull request by marie-j**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-32456, DTRSD-32950
| License          | BSD 3-Clause

### CODE REVIEW

**Review by frenautvh — APPROVED** [review]

**Review by antleblanc — APPROVED** [review]

**Review by JeremyDec — DISMISSED** [review]

**Review by Jisay — DISMISSED** [review]

**Review by cbourgois — APPROVED** [review]

**Comment by marie-j** [comment]
Rebased on `develop`

**Comment by antleblanc** [comment]
@marie-j Could you please resolve existing conflict?
Thank you!

**Comment by antleblanc** [comment]
Rebasing on `release/2021-w15` branch.

**Comment by antleblanc** [comment]
Rebased successfully on `release/2021-w15` branch.

**Pull request merged**
