### PR TITLE
fix(dedicated): remove period in autorenew action

### PR DESCRIPTION
**Pull request by frenautvh**
| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | internal DTRSD-30192
| License          | BSD 3-Clause

## Description

Remove period in action description

- [x] Retrieve TRANS-32692

### CODE REVIEW

**Review by antleblanc — DISMISSED** [review]

**Comment by ovh-cds** [comment]
CDS Report translator-push#14809.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translations-checker#14810.0 ✘  
* Stage 1
  * Check ✘

**Comment by ovh-cds** [comment]
CDS Report translations-checker#14812.0 ✘  
* Stage 1
  * Check ✘

**Review by JeremyDec — APPROVED** [review]

**Review by marie-j — DISMISSED** [review]

**Comment by antleblanc** [comment]
Pulling translations.

**Comment by antleblanc** [comment]
Translations has been pulled successfully.

**Review by antleblanc — APPROVED** [review]

**Review by JeremyDec — APPROVED** [review]

**Pull request merged**
