### PR TITLE
New release

### PR DESCRIPTION
**Pull request by antleblanc**
# 📦 New release

Approximate release date: 📆 27/05/2020

### :rocket: Features

- [x] MANAGER-4806 (https://github.com/ovh/manager/pull/2901)

### :bug: Bug Fixes

- [ ] MANAGER-4992 (#2847)

### :rocket: Features

- [x] MANAGER-3330 - feat(domain.webhosting): update order (#2799)
- [x] MANAGER-3729 - feat(domain.zone): detach zone (#2833)
- [x] MANAGER-3327 (#2798)

### :bug: Bug Fixes

- [x] DTRSD-12506 (#3001)

### :rocket: Features

- [x] MANAGER-4962 - feat(account.contacts): sort services consistently by name and category (#2783)
- [x] MANAGER-2414

### :bug: Bug Fixes

_to be defined_

### ♻️ Refactor

33a366d - refactor(billing.payment.method): retrieve current user from root state (#2968)
02e5b79 - refactor(user-contracts): use import/export statements (#2742)

### :rocket: Features

_to be defined_

### :bug: Bug Fixes

_to be defined_

### :rocket: Features

_to be defined_

### :bug: Bug Fixes

- [x] DTRSD-10442 - fix(navbar): notification text not visible in dark mode (#2732)

### :rocket: Features

- [x] MANAGER-5053 - feat(telephony.billingaccount.administration): preload all groups (#2810)
- [x] UXCT-271 - feat(telephony.order.phone): add message for rma (#2896)

### :bug: Bug Fixes

- [x] UXCT-265 - fix(overthebox): remove useless update application action (#2898)
- [x] UXCT-286 (#2997)

---

#### :rocket: Features

7e4d76c - feat: autopay detach if it is free (#2833)

#### :books: Documentation

9bff1c5 - docs(workflow): update options (#2833)

#### 💥 Breaking Change

- [ ] MANAGER-4419 - feat(tuc-editable-service-name): make component work with ui-header (#2275)

#### ⚡ Performance

7cc6cff - perf: use lodash-es instead of lodash (#3039)

#### ⚡ Performance

3af0d7c - perf: remove lodash dependency (#3048)

### 💅 Style

- [ ] ~~MANAGER-4955 (#2848)~~

### 🚚 Import modules

- [x] MANAGER-4500 - Import @ovh-ux/ng-ovh-actions-menu (#2982)
- [x] MANAGER-4515 - Import @ovh-ux/ng-ovh-otrs (#2895)
- [x] MANAGER-4517 - Import @ovh-ux/ng-ovh-responsive-popover (#2984)
- [x] MANAGER-4519 - Import @ovh-ux/ng-ovh-sidebar-menu (#2987)

### 📚 Documentation

d5e81d6 - docs: update CONTRIBUTORS file
c86b1b3 - docs: update MAINTAINERS file
3097d1a - docs: remove extra signed-off-by and co-authored-by from CHANGELOG
c1dd17e - docs(contributing): update command to format code (#3037)

### 🎏 Translations

- [ ] TRANS-25238 

### 🤝 Contributors

- @julieni

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report translator-push#7956.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translator-push#7965.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translator-push#7970.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translator-push#7971.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translations-checker#7973.0 ✘  
* Stage 1
  * Check ✘

**Comment by julieni** [comment]
MANAGER-4962 should be in Transversal section I think, or in Dedicated section from source code location point of view

**Comment by antleblanc** [comment]
> MANAGER-4962 should be in Transversal section I think, or in Dedicated section from source code location point of view

Good catch! Thank you! I have updated the **Description**.

**Comment by ovh-cds** [comment]
CDS Report installation#12293.0 ✘  
* Stage 1
  * Install ✘

**Comment by ovh-cds** [comment]
CDS Report translations-checker#8028.0 ✘  
* Stage 1
  * Check ✘

**Comment by ovh-cds** [comment]
CDS Report build#12317.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build#12401.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report translations-checker#422.0 ✘  
* Stage 1
  * Check ✘

**Comment by ovh-cds** [comment]
CDS Report translations-checker#8272.0 ✘  
* Stage 1
  * Check ✘

**Pull request merged**
