### PR TITLE
feat(account-contacts): sort services consistently by name and category

### PR DESCRIPTION
**Pull request by julieni**

### CODE REVIEW

**Comment by julieni** [comment]
Thanks @antleblanc.

I  have another patch ready: filter services by admin/tech/billing contact. The only "problem" is that all services contacts must be loaded before the UI is ready, that means 1+N requests to the API.

Any progress on an aggregation request to get services with contacts in 1 request? We already talked about this.

**Comment by antleblanc** [comment]
**Internal ticket reference**: MANAGER-4962

**Comment by ovh-cds** [comment]
CDS Report installation#11498.0 ✘  
* Stage 1
  * Install ✘

**Comment by antleblanc** [comment]
@julieni As for now we have no news to share regarding the aggregation.
It's planned in the Roadmap but I cannot guarantee any due date for now.

**Comment by julieni** [comment]
> @julieni As for now we have no news to share regarding the aggregation.
> It's planned in the Roadmap but I cannot guarantee any due date for now.

Ok, for the moment I submitted PR https://github.com/ovh/manager/pull/2809 with multiple requests to the API. Will improve it when the call is available.

**Pull request merged**
