### PR TITLE
New release

### PR DESCRIPTION
**Pull request by antleblanc**
# 📦 New release

Approximate release date: 📆 17/03/2021

### :sparkles: Features

- [x] MANAGER-6144 - feat(vps): add tracking on upgrade and upscale (#4432)
- [x] MANAGER-5383 - Solarsteein Bare Metal Cloud (#3780)
- [x] MANAGER-6558 -  feat(dedicated.billing.autorenew): add servicetype to tracking (#4549)

### :bug: Bug Fixes

- [x] MANAGER-6343 - fix(billing.autorenew): update autorenew tracking (#4476)

<details>
<summary>Other bug fixes</summary><br>

4159de4 - fix(billing.autorenew): replace Server call with /services (#4526)
</details>

### :sparkles: Features

- [x] MANAGER-5382 - Solarsteein Web Cloud (#3779)

### 🐛 Fixes
- [x] MANAGER-6574 - fix: avoid to override already imported stylesheet (#4594)

### :sparkles: Features

- [x] MANAGER-6222 - feat(voip.billing-account): add alert for suspended billing account (#4456)
- [x] MANAGER-6234 - feat(line): add antihack alert (#4466)
- [x] MANAGER-6235 - feat(telecom): add voicemail password checkbox (#4478)

### :bug: Bug Fixes

- [x] MANAGER-6244 - fix(alias): allow resiliation (#4565)
- [x] UXCT-373 - fix(move.buildingdetails): rename building reference to reference (#4400)
- [x] DTRSD-30994 - fix/telephony contact (#4571)

---

#### :bug: Bug fixes

- [x] MANAGER-5814 - fix(tracking): update defaults initialization (#4595)

#### 🐛 Bug fixes

- fix(i18n): remove unused locales (#4598) 

#### :bug: Bug Fixes

- [ ] MANAGER-6500 - fix(locale): add missing getUserLocale method (#4498)

#### 🐛 Bug Fixes
- [x] MANAGER-6570 - fix(dedicated-cloud): update datacenter subitem state (#4593) 

### ♻️  Refactor
- [ ] fix: remove non needed component (#4563)

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report translator-push#14921.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translator-push#14924.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translator-push#14925.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translator-push#14953.0 ✘  
* 
  * push ✘

**Review by marie-j — APPROVED** [review]

**Pull request merged**
