### PR TITLE
feat(wuc): add helper with engine version compare method

### PR DESCRIPTION
**Pull request by JeremyDec**
## 🚀 Feature
Add helper to sort engine version, see MANAGER-4121

Signed-off-by: Jérémy De-Cesare <jeremy.de-cesare@corp.ovh.com>

### CODE REVIEW

**Comment by JeremyDec** [comment]
@frenautvh "engine" concerns for example cloud database server engines ("MySQL 5.7"). Ok it is generic, but I guess that not just Cloud db have server engines who have this version format. Maybe "serverEngineVersionCOmpare" would be clearer ?

I've created it in wuc, as this is used for Cloud db.

**Comment by frenautvh** [comment]
> @frenautvh "engine" concerns for example cloud database server engines ("MySQL 5.7"). Ok it is generic, but I guess that not just Cloud db have server engines who have this version format. Maybe "serverEngineVersionCOmpare" would be clearer ?
> 
> I've created it in wuc, as this is used for Cloud db.

The naming should describe what the function does. In your case your function is sorting some data using a label then if it's equals use the version.

It's really a bad practice to create helper functions for such simple tasks

you should delete this code and simply use _.sortBy(data, ["engineLabel", "engineVersion"])

**Comment by frenautvh** [comment]
```_.sortBy(data, ["engineLabel", o => parseFloat(o.engineVersion)])```

**Comment by JeremyDec** [comment]
Ok doing

**Pull request closed without merging**
