### PR TITLE
fix(i18n): add missing translations [CDS 897]

### PR DESCRIPTION
**Pull request by mohammed-zahaf**
Signed-off-by: CDS Translator Agent <opensource@ovh.net>

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-6683
| License          | BSD 3-Clause

## Description

Goals of this is to complete the missed DE trad keys

### CODE REVIEW

**Comment by mohammed-zahaf** [comment]
Hello @antleblanc, we received the missed trad keys for DE.

**Review by antleblanc — APPROVED** [review]

**Comment by mohammed-zahaf** [comment]
Hello @antleblanc, i think we can add this PR into a release.

**Comment by antleblanc** [comment]
Hi @mohammed-zahaf!

Following Pull Request has already been merged. Will be included into the next release.

Thank you!

**Comment by mohammed-zahaf** [comment]
Ok, nice.

**Pull request merged**
