### PR TITLE
fix(deps): upgrade ovh-api-services to v11.0.1

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | no
| License          | BSD 3-Clause

### :arrow_up: Upgrade

215295d - fix(deps): upgrade ovh-api-services to v11.0.1

uses: `$ yarn upgrade-interactive --latest ovh-api-services`
- ovh-api-services@11.0.1

### :link: Related

- ovh-ux/ovh-api-services#317

### :house: Internal

No quality check required.

Signed-off-by: Antoine Leblanc <antoine.leblanc@ovhcloud.com>

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#17265.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report test#17265.0 ✔ 
* Stage 1
  * lint ✔ 
  * SemVer ✔

**Comment by ovh-cds** [comment]
CDS Report test#17265.0 ✔ 
* Stage 1
  * lint ✔ 
  * SemVer ✔

**Comment by ovh-cds** [comment]
CDS Report build#17265.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report installation#17265.0 ✔ 
* Stage 1
  * Install ✔

**Review by JeremyDec — APPROVED** [review]

**Pull request merged**
