### PR TITLE
feat(ng-ovh-responsive-tabs): replace lodash with lodash-es

### PR DESCRIPTION
**Pull request by frenautvh**
Signed-off-by: frenauvh <florian.renaut@corp.ovh.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          |
| License          | BSD 3-Clause

## Description

Replace lodash with lodash-es to reduce bundle size

### CODE REVIEW

**Comment by antleblanc** [comment]
@frenautvh Regarding the changes (and the label chosen) do you think it could deserve a commit type [`perf`](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type) instead?.

**Comment by FredericEspiau** [comment]
@antleblanc I don't think so because it's not only a change on the `perf` but also on the `build` system, so I would have gone for `build` myself

**Comment by frenautvh** [comment]
> @antleblanc I don't think so because it's not only a change on the `perf` but also on the `build` system, so I would have gone for `build` myself

@antleblanc @FredericEspiau perf / build it's tricky both seems to work. I would just build just because i don't perform any performance tweaks on the code and just replace a dependency. Is that ok for both of you?

**Comment by antleblanc** [comment]
> @antleblanc I don't think so because it's not only a change on the `perf` but also on the `build` system, so I would have gone for `build` myself

Since we are decreasing the bundle size, it feels more natural to be marked as perf.
It is the main topic that this Pull Request is addressing.

**Comment by antleblanc** [comment]
> > @antleblanc I don't think so because it's not only a change on the `perf` but also on the `build` system, so I would have gone for `build` myself
> 
> @antleblanc @FredericEspiau perf / build it's tricky both seems to work. I would chooose build just because i don't perform any performance tweaks on the code and just replace a dependency. Is that ok for both of you?

The `build` commit type won't trigger a new version on the affected package.

I encourage you to use a commit type `perf` to be able to publish a new version on the npm registry.

**Comment by antleblanc** [comment]
@frenautvh Could you please resolve existing conflict in order to be able to merge it? Thank you!

**Comment by FredericEspiau** [comment]
@antleblanc 😅 indeed `perf` is better then

**Pull request merged**
