### PR TITLE
feat(storage.cold-storage): edit the storage menu item

### PR DESCRIPTION
**Pull request by brofik**
| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-10291`  
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-10291 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

### CODE REVIEW

**Review by anooparveti — COMMENTED** [review]
Dont we need to change in the new sidebar?
https://github.com/ovh/manager/blob/master/packages/manager/apps/container/src/container/nav-reshuffle/sidebar/navigation-tree/services/publicCloud.ts#L113

**Comment by brofik** [comment]
> **question:** Dont we need to change in the new sidebar? https://github.com/ovh/manager/blob/master/packages/manager/apps/container/src/container/nav-reshuffle/sidebar/navigation-tree/services/publicCloud.ts#L113

yes we do.

**Review by anooparveti — CHANGES_REQUESTED** [review]
Can you please make the change in new sidebar as well?

**Comment by brofik** [comment]
> Can you please make the change in new sidebar as well?

Sure. 
Where is the new sidebar module located in the manager project ?

**Review by sachinrameshn — APPROVED** [review]

**Pull request merged**
