### PR TITLE
Feat/manager 9655: custom clipboard component

### PR DESCRIPTION
**Pull request by mohammed-zahaf**
| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-9093`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-9655
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
1. create a component to copy content from input password to clipboard

### CODE REVIEW

**Review by anooparveti — COMMENTED** [review]
**question:** Can we use existing clipboard component https://ovh.github.io/ovh-ui-kit/?path=/story/design-system-components-clipboard-webcomponent--default ?

**Comment by mohammed-zahaf** [comment]
> **question:** Can we use existing clipboard component https://ovh.github.io/ovh-ui-kit/?path=/story/design-system-components-clipboard-webcomponent--default ?

No unfortunately, the default component don't provide the requested behavior.
Have a look:
image

**Review by anooparveti — APPROVED** [review]

**Comment by marie-j** [comment]
> > **question:** Can we use existing clipboard component https://ovh.github.io/ovh-ui-kit/?path=/story/design-system-components-clipboard-webcomponent--default ?
> 
> No unfortunately, the default component don't provide the requested behavior. Have a look: image

And instead could we upgrade the behaviour of existing component to support password type ?

**Review by vks-ovh — APPROVED** [review]

**Comment by mohammed-zahaf** [comment]
> > > **question:** Can we use existing clipboard component https://ovh.github.io/ovh-ui-kit/?path=/story/design-system-components-clipboard-webcomponent--default ?
> > 
> > 
> > No unfortunately, the default component don't provide the requested behavior. Have a look: image
> 
> And instead could we upgrade the behavior of existing component to support password type ?

Yes it could be great.
For the moment we used it on two different `pci.storages` module.
If i notice we have to use it on others  project part, i would like to complete it.

Thanks for suggestion.

**Pull request merged**
