### PR TITLE
Update Data Processing section

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-5026
| License          | BSD 3-Clause

## Description

This PR add some click tracking to the Data Processing service pages, as requested by Commerce and Marketing teams.
The Data Processing logo was also updated and the service is now tagged as new instead of beta
The service will become available on CA as well

### 🔗 Related

- #3063

### 🔖 TODOs

- [x] TRANS-26084

### 🤝 Contributors

- @impolitepanda

### CODE REVIEW

**Comment by frenautvh** [comment]
"This PR add some click tracking to the Data Processing service pages"

this PR is doing a lot more than that (price manipulation etc), what is the scope ?

**Comment by frenautvh** [comment]
> "This PR add some click tracking to the Data Processing service pages"
> 
> this PR is doing a lot more than that (price manipulation etc), what is the scope ?

maybe just a rebase needed ?

**Comment by antleblanc** [comment]
> > "This PR add some click tracking to the Data Processing service pages"
> > this PR is doing a lot more than that (price manipulation etc), what is the scope ?
> 
> maybe just a rebase needed ?

@frenautvh Thanks for pointing out this. The scope of this Pull Request is still about **Data Processing** but there is a change required for the **Catalog Price** component.

@impolitepanda Maybe we can consider updating the **Pull Request** description in order to mention that also the Catalog Price component has changed.

**Comment by impolitepanda** [comment]
> @impolitepanda Maybe we can consider updating the **Pull Request** description in order to mention that also the Catalog Price component has changed.

Doing :)

**Comment by antleblanc** [comment]
Rebased on `master` branch.

**Pull request merged**
