### PR TITLE
Add some headset pictures choices in Telecom  #MANAGER-12562

### PR DESCRIPTION
**Pull request by blemoineovh**
| Question         | Answer
| ---------------- | ---
| Branch?          |`develop` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-12562 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description
Added some references to 4 new pictures in the headset list
## Related
nothing more

### CODE REVIEW

**Review by sachinrameshn — CHANGES_REQUESTED** [review]
Your commit message is wrong It should be like below: 

feat|fix(universe): commit short description

ref: MANAGER-XXXXX

Signed-off-by : github account user

**Comment by sachinrameshn** [comment]
Also can you fill out Q & A part of PR description along with relevant sections ?

**Comment by blemoineovh** [comment]
@sachinrameshn i fixed the PR with your recommendations

**Comment by sachinrameshn** [comment]
> @sachinrameshn i fixed the PR with your recommendations

I missed to note another one your branch name is not proper one. It should be either feat/xxxxxxx in case of feature change or fix/xxxxxxx in case of a bug fix or refactor/xxxxxxxx in case of refactor work.

**Review by BrunoMarquesOVH — APPROVED** [review]

**Comment by blemoineovh** [comment]
> > @sachinrameshn i fixed the PR with your recommendations
> 
> I missed to note another one your branch name is not proper one. It should be either feat/xxxxxxx in case of feature change or fix/xxxxxxx in case of a bug fix or refactor/xxxxxxxx in case of refactor work.

ok i created a new branch, i will reopen a new PR

**Comment by blemoineovh** [comment]
changed branch name to this PR: https://github.com/ovh/manager/pull/10409

**Pull request closed without merging**
