### PR TITLE
feat: add favicon

### PR DESCRIPTION
**Pull request by marie-j**
| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/manager-hub`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-4641
| License          | BSD 3-Clause

## Description

- Add favicon and title for Manager Hub app

### CODE REVIEW

**Comment by frenautvh** [comment]
are you sure assets will be bundled in the dist ?

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#10404.0 ✘  
* 
  * Build ✘

**Comment by antleblanc** [comment]
Related to #1686

@frenautvh You're right!

The webpack configuration needs to be updated.

You can refer to this example: https://github.com/ovh/manager/pull/1686/files#diff-b580788571e2833ddd12abc58f2f296dR43

**Comment by marie-j** [comment]
@frenautvh Indeed, nice catch ! I'll update

**Pull request merged**
