### PR TITLE
Feat/hosting email activate

### PR DESCRIPTION
**Pull request by radireddy**
MIAW-email option

order/activate email offer using Agora API's 

Please only review commit https://github.com/ovh/manager/commit/e88b5c3bc6b84af56b7480217f2c79ab8959e356

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#7805.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#7806.0 ✘  
* 
  * Build ✘

**Comment by marie-j** [comment]
Maybe this branch should be rebased on `feat/miaw` as some commits are not part of this feature

**Comment by marie-j** [comment]
@radireddy `ovh-api-services` have been bumped : https://github.com/ovh/manager/pull/1917

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#7866.0 ✘  
* 
  * Build ✘

**Pull request closed without merging**
