### PR TITLE
Upgrade both ESLint and Prettier

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | no
| License          | BSD 3-Clause

## Description

Original Pull Request: #4023

Following `bugfix/upgrade-eslint-prettier` branch has been rebased on `develop` branch.
I cannot reopen previous Pull Request due to the rebase.

Following Pull Requests has been merged:

- #3778
- #3779
- #3780

### :arrow_up: Upgrade

127a943 - build: bump both prettier and eslint configuration

### :construction_worker: Build

4b527fe - build: remove extra eslint configuration

### :bug: Bug Fixes

a99f5d5 - fix(peer-deps): add missing peer deps

### :nail_care: Style

60b398e - style: apply prettier rules
e5d8137 - style: apply prettier rules

### :house: Internal

No quality check required.

### CODE REVIEW

**Review by zakariasahmane — DISMISSED** [review]
Looks good to me !

**Review by JeremyDec — COMMENTED** [review]
Hello @antleblanc, there is a conflict related to `flatpickr` version to resolve

**Comment by antleblanc** [comment]
Thanks @JeremyDec for pointing out the conflicts.
Rebasing on `develop` branch in order to resolve existing conflicts.

**Comment by antleblanc** [comment]
Rebased successfully on `develop` branch.

**Review by JeremyDec — APPROVED** [review]

**Comment by marie-j** [comment]
@antleblanc  You have conflicts (again) 😕

**Review by Jisay — APPROVED** [review]

**Comment by antleblanc** [comment]
> @antleblanc You have conflicts (again) confused

Yep! I need to find the right timing to be able to rebase and merge this Pull Request.

I will keep you posted. Thanks

**Review by Jisay — APPROVED** [review]

**Comment by antleblanc** [comment]
Right timing need to be defined so for now I will close this Pull Request.
Thank you!

**Pull request closed without merging**
