### PR TITLE
fix PUD-1111 (pci.storage.databases):  add tooltip for default db suppression action

### PR DESCRIPTION
**Pull request by jperchoc**
PUD-1111

Signed-off-by: Jonathan Perchoc <jonathan.perchoc@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #PUD-1111
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Add a tooltip on the disabled suppress action for the default database

### :flags: Translations

- [x] TRANS-40432

### CODE REVIEW

**Review by antleblanc — APPROVED** [review]
Changes looks good to me.
Looks like a Feature rather than a Bugfix.

**Review by zakariasahmane — COMMENTED** [review]
Changes looks good, but target branch is `master` and it doesn't look like a `hotfix`. I think target branch should be `develop`.

**Review by JeremyDec — APPROVED** [review]

**Review by anooparveti — DISMISSED** [review]

**Comment by jperchoc** [comment]
I've changed the target to `develop`, thanks !

**Review by JeremyDec — APPROVED** [review]

**Review by marie-j — APPROVED** [review]

**Comment by antleblanc** [comment]
Pulling translation.

**Review by antleblanc — APPROVED** [review]

**Review by JeremyDec — APPROVED** [review]

**Pull request merged**
