### PR TITLE
fix(catalog-price): fix binding for dynamic price

### PR DESCRIPTION
**Pull request by XciD**
| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DGSD-348, DTRSD-39041
| License          | BSD 3-Clause

## Description

Remove one time binding for US

### CODE REVIEW

**Review by marie-j — DISMISSED** [review]

**Review by JeremyDec — APPROVED** [review]

**Review by Jisay — APPROVED** [review]

**Comment by antleblanc** [comment]
@XciD Commit type used here is a `feat` whereas you are mentioning in the Pull Request description that it's a `Bug Fix`.

According to the diff, it seems that you are addressing a **Bug**. Could  you please confirm?

Additional resource about commit conventions (if needed): https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type

Thank you!

**Comment by XciD** [comment]
Sorry for that, yes it's clearly a bug

**Review by antleblanc — DISMISSED** [review]

**Comment by XciD** [comment]
@antleblanc any update ? It’s a bug in CA

**Comment by antleblanc** [comment]
@XciD I've added an additional commit to be able to perform some test regarding this patch.

**Review by antleblanc — APPROVED** [review]

**Comment by antleblanc** [comment]
Updating target branch to `release/2021-w26`.

**Comment by antleblanc** [comment]
Rebasing on `release/2021-w26` branch in order to be able to rewrite first commit.

**Comment by antleblanc** [comment]
Rebased successfully on `release/2021-w26` branch.

**Pull request merged**
