### PR TITLE
feat(dedicated): make zpool name customizable for ZFS and remove some errors

### PR DESCRIPTION
**Pull request by JayBeeDe**
| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes/no
| Breaking change? | no
| Tickets          | Fix MANAGER-11031
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

Make zpool name customizable in the partitionning wizzard and remove the following errors:
-  "This volume name is already in use" -> already handled by API (unique volume name for LVM but can be the same value when filesystem is ZFS)
- "The volume name must not contain special characters, must not exceed 16 characters, and must be different from pvmove and snapshot" -> already handled by API (same error for LVM but check is different when filesystem is ZFS)
- "All LV partitions must have the same RAID" -> supported by all installers, except for debian 9 ARM that will be EoL very soon: LVM has been disabled for this template in the meantime
- "You cannot have a logical partition and an LV partition at the same time" -> supported, has always been supported by API

## Related

MANAGER-11031

### CODE REVIEW

**Review by sachinrameshn — APPROVED** [review]

**Review by anooparveti — DISMISSED** [review]

**Comment by JayBeeDe** [comment]
Sorry I was missing something in the process regarding the translation...

**Comment by JayBeeDe** [comment]
@anooparveti  @sachinrameshn You can re-ack the PR, nothing has changed, just the translations have been pulled in the meantime

**Comment by JayBeeDe** [comment]
The translation commit is missing.... Checking with @anooparveti how to get it back

**Comment by JayBeeDe** [comment]
> Please request another translation pull to complete this PR

https://cds.ovhcloud.tools/project/UXMAN/workflow/translator-push-manager/run/39000/node/27442236?name=translator-push
https://jira.ovhcloud.tools/browse/TRANS-51736
Waiting translation team

**Comment by JayBeeDe** [comment]
> Please request another translation pull to complete this PR

@y4nnL 

https://cds.ovhcloud.tools/project/UXMAN/workflow/translator-push-manager/run/39000/node/27442236?name=translator-push
https://jira.ovhcloud.tools/browse/TRANS-51736
FYI: Waiting translation team

**Comment by JayBeeDe** [comment]
> Please request another translation pull to complete this PR

@y4nnL 

https://cds.ovhcloud.tools/project/UXMAN/workflow/translator-push-manager/run/39000/node/27442236?name=translator-push
https://jira.ovhcloud.tools/browse/TRANS-51736
FYI: Waiting translation team

**Review by y4nnL — APPROVED** [review]

**Pull request merged**
