### PR TITLE
feat(logs): rename `Elasticsearch` products to `OpenSearch`

### PR DESCRIPTION
**Pull request by pdepaepe**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-9576
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Hello,

As announced here: https://bare-metal-servers.status-ovhcloud.com/incidents/n6t88vsqsvm3, the 15th of June, we will replace

- the "Elasticsearch" backend of Logs Data Platform to "OpenSearch"
- and so the "Kibana" instances to "OpenSearch Dashboards" ones

If new API endpoints are already available to handle that, we will firstly in this PR, simply rename references.
An other pull request will come later to use the new endpoints.

As always, thanks for your time on this.

Pierre De Paepe on behalf of Logs Data Platform

### CODE REVIEW

**Review by anooparveti — DISMISSED** [review]
According to https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations, the developers are not supposed to modify the contents of translations files except `fr_FR`. So could you please only include only `fr_FR` files in the PR. 
Let me know if you need any more information.

**Comment by pdepaepe** [comment]
> According to https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations, the developers are not supposed to modify the contents of translations files except `fr_FR`. So could you please only include only `fr_FR` files in the PR. Let me know if you need any more information.

I understand but as only the software has been renamed and that they are (by definition) used **as is** in all languages, why asking translators help?

**Comment by vks-ovh** [comment]
Don't see any ticket reference.

**Review by Jisay — DISMISSED** [review]

**Review by antleblanc — APPROVED** [review]

**Review by anooparveti — DISMISSED** [review]

**Comment by antleblanc** [comment]
Pulling translations.

**Review by antleblanc — APPROVED** [review]

**Review by JeremyDec — APPROVED** [review]

**Review by anooparveti — APPROVED** [review]

**Pull request merged**
