### PR TITLE
Feat/solarsteein web

### PR DESCRIPTION
**Pull request by marie-j**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-5382
| License          | BSD 3-Clause

## Description

- [x] https://github.com/ovh/manager/pull/3344
- [x] https://github.com/ovh/manager/pull/3410
- [x] https://github.com/ovh/manager/pull/3412
- [x] https://github.com/ovh/manager/pull/3413
- [x] https://github.com/ovh/manager/pull/3415
- [x] https://github.com/ovh/manager/pull/3416
- [x] https://github.com/ovh/manager/pull/3418
- [x] https://github.com/ovh/manager/pull/3419
- [x] https://github.com/ovh/manager/pull/3422
- [x] https://github.com/ovh/manager/pull/3431
- [x] https://github.com/ovh/manager/pull/3432
- [x] https://github.com/ovh/manager/pull/3435
- [x] https://github.com/ovh/manager/pull/3436
- [x] https://github.com/ovh/manager/pull/3437
- [x] https://github.com/ovh/manager/pull/3437
- [x] https://github.com/ovh/manager/pull/3438
- [x] https://github.com/ovh/manager/pull/3439
- [x] https://github.com/ovh/manager/pull/3654
- [x] https://github.com/ovh/manager/pull/3659
- [x] https://github.com/ovh/manager/pull/3661
- [x] https://github.com/ovh/manager/pull/3664
- [x] https://github.com/ovh/manager/pull/3672
- [x] https://github.com/ovh/manager/pull/3675
- [x] https://github.com/ovh/manager/pull/3679
- [x] https://github.com/ovh/manager/pull/3680
- [x] https://github.com/ovh/manager/pull/3682
- [x] https://github.com/ovh/manager/pull/3684
- [x] https://github.com/ovh/manager/pull/3719
- [x] Extract from fc2c2af6f6e0397963fe8bca9bcfbf00608f21aa
- [x] https://github.com/ovh/manager/pull/3786

## Related

- [ ] https://github.com/ovh/manager/pull/3780 (needs sync for Exchange)
- [x] TRANS-32495

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#15782.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report test#15904.0 ✘  
* Stage 1
  * lint ✔ 
  * SemVer ✘

**Comment by ovh-cds** [comment]
CDS Report build#16793.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build#16793.1 ✘  
* 
  * Build ✘

**Review by antleblanc — APPROVED** [review]

**Pull request merged**
