### PR TITLE
Feat/solarsteein server

### PR DESCRIPTION
**Pull request by marie-j**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-5383
| License          | BSD 3-Clause

## Description

- [x] https://github.com/ovh/manager/pull/3368
- [x] https://github.com/ovh/manager/pull/3545
- [x] https://github.com/ovh/manager/pull/3553
- [x] https://github.com/ovh/manager/pull/3554
- [x] https://github.com/ovh/manager/pull/3653
- [x] https://github.com/ovh/manager/pull/3691
- [x] https://github.com/ovh/manager/pull/3696
- [x] https://github.com/ovh/manager/pull/3697
- [x] https://github.com/ovh/manager/pull/3723
- [x] https://github.com/ovh/manager/pull/3724
- [x] https://github.com/ovh/manager/pull/3751
- [x] Extract from fc2c2af6f6e0397963fe8bca9bcfbf00608f21aa
- [x] https://github.com/ovh/manager/pull/3539
- [x] https://github.com/ovh/manager/pull/3648
- [x] https://github.com/ovh/manager/pull/3703
- [x] https://github.com/ovh/manager/pull/3706
- [x] https://github.com/ovh/manager/pull/3718
- [x] https://github.com/ovh/manager/pull/3756
- [x] https://github.com/ovh/manager/pull/3757
- [x] https://github.com/ovh/manager/pull/3799
- [x] https://github.com/ovh/manager/pull/4042

## Related
- [x] https://github.com/ovh/manager/pull/3779 (needs sync for Exchange )
- [x] feature-availability#64
- [x] TRANS-32235

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report test#16848.0 ✘  
* Stage 1
  * lint ✘  
  * SemVer ✔

**Comment by ovh-cds** [comment]
CDS Report build#17103.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report test#17108.0 ✘  
* Stage 1
  * lint ✔ 
  * SemVer ✘

**Review by antleblanc — APPROVED** [review]

**Comment by antleblanc** [comment]
Conflict on `yarn.lock` file.

Rebasing on `develop` branch (got 1 approval)

**Comment by antleblanc** [comment]
Conflict solved.

Rebased successfully on `develop` branch.

**Review by antleblanc — APPROVED** [review]

**Pull request merged**
