### PR TITLE
refactor(cloud): remove cloud app, redirect to dedicated app

### PR DESCRIPTION
**Pull request by frenautvh**
| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-6249
| License          | BSD 3-Clause

## Description

Delete legacy cloud application. Add a redirection vers dedicated application.

### CODE REVIEW

**Comment by frenautvh** [comment]
changes can be reviewed here : https://github.com/ovh/manager/tree/73df4f1be023ba8731e893a676115c4153727dab/packages/manager/apps/cloud

**Review by cbourgois — APPROVED** [review]

**Review by marie-j — DISMISSED** [review]

**Comment by antleblanc** [comment]
Rebasing on `develop` branch in order to solve existing conflicts.

**Conflicting files**:
```txt
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/ip/failover/import/translations/Messages_en_GB.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/ip/failover/import/translations/Messages_fr_CA.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/ip/failover/import/translations/Messages_pt_PT.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/privateNetwork/dialog/translations/Messages_en_GB.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/privateNetwork/dialog/translations/Messages_fr_CA.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/translations/Messages_en_GB.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/translations/Messages_fr_CA.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/delete/translations/Messages_en_GB.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/delete/translations/Messages_es_ES.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/delete/translations/Messages_fr_CA.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/delete/translations/Messages_it_IT.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/delete/translations/Messages_pt_PT.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/monitoring/translations/Messages_en_GB.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/monitoring/translations/Messages_fr_CA.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/rescue/translations/Messages_en_GB.json
packages/manager/apps/cloud/client/app/cloud/project/compute/infrastructure/virtualMachine/rescue/translations/Messages_fr_CA.json
packages/manager/apps/vps/package.json
```

**Comment by antleblanc** [comment]
Rebased successfully on `develop` branch.

**Comment by antleblanc** [comment]
Rebasing on `develop` branch in order to solve existing conflicts.

**Comment by antleblanc** [comment]
Rebased successfully on `develop` branch.

**Pull request merged**
