### PR TITLE
refactor: remove unused welcome module

### PR DESCRIPTION
**Pull request by antleblanc**
## 🗑 Refactor

a6af49e - refactor: remove unused welcome module

## 👀 Checks

```sh
$ git grep "@ovh-ux/manager-welcome" -- '*.js' | wc -l
       0

$ git grep "@ovh-ux/manager-welcome" -- '*.json'
packages/manager/modules/welcome/package.json:  "name": "@ovh-ux/manager-welcome",
packages/manager/modules/welcome/package.json:    "start": "lerna exec --stream --scope='@ovh-ux/manager-welcome' --include-dependencies -- yarn run build",
packages/manager/modules/welcome/package.json:    "start:dev": "lerna exec --stream --scope='@ovh-ux/manager-welcome' --include-dependencies -- yarn run dev",
packages/manager/modules/welcome/package.json:    "start:watch": "lerna exec --stream --parallel --scope='@ovh-ux/manager-welcome' --include-dependencies -- yarn run dev:watch"
```

## 🏠 Internal

No quality check required.

Signed-off-by: Antoine Leblanc <ant.leblanc@gmail.com>

### CODE REVIEW

**Comment by FredericEspiau** [comment]
Shouldn't we keep it for documentation value though ?

**Comment by antleblanc** [comment]
> Shouldn't we keep it for documentation value though ?

Relying on the following command `$ yarn run generate:module` might be better.

A first draft is available here: https://ovh.github.io/manager/guide/scripts.html#generate-a-module-or-an-application

Let me know what do you think. Thanks!

**Comment by FredericEspiau** [comment]
@antleblanc I'm talking about documentation value, not generation :)

`welcome` could show the current best practices, it could make it easy to read how to code

The generator will... well generate the template for a basic app, it shouldn't contain much calls to the API, much states, and so on :)

**Comment by antleblanc** [comment]
@FredericEspiau @marie-j I understand your point when it comes to the **documentation** value.

The codebase of the monorepo should reflect the best practices at some point but yes currently we are relying with some **legacy** codebase.

What I want to mention here is:
- The module is not used.
- The module is not documented.
- The module is not used as a documentation entry point.

I have mentioned the small generators that can scaffold basics module or application.
Theses pieces are here to act also as a documentation level to demonstrate what is our best practices.

I had mind that maybe we can improve the documentation of these tools.

**Pull request merged**
