### PR TITLE
feat(chatbot): enable chatbot for CA subsidiaries

### PR DESCRIPTION
**Pull request by cbourgois**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix MANAGER-5302
| License          | BSD 3-Clause

## Description

Enable chatbot for CA, QC, WE, WS subsidiaries

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report test-manager_2#13459.0 ■   
* Stage 1
  * e2e -   
  * lint ✔ 
  * SemVer ■

**Comment by ovh-cds** [comment]
CDS Report test-manager_2#13459.0 ■   
* Stage 1
  * e2e -   
  * lint ✔ 
  * SemVer ■

**Comment by ovh-cds** [comment]
CDS Report build#13459.0 ■   
* 
  * Build ■

**Comment by ovh-cds** [comment]
CDS Report build#13459.0 ■   
* 
  * Build ■

**Comment by ovh-cds** [comment]
CDS Report build#13461.0 ■   
* 
  * Build ■

**Comment by ovh-cds** [comment]
CDS Report build#13461.1 ■   
* 
  * Build ■

**Comment by ovh-cds** [comment]
CDS Report build#13461.1 ■   
* 
  * Build ■

**Comment by cbourgois** [comment]
Rebased on `develop`

**Review by antleblanc — DISMISSED** [review]

**Review by frenautvh — DISMISSED** [review]

**Review by marie-j — DISMISSED** [review]

**Comment by cbourgois** [comment]
Need to rebase

**Comment by cbourgois** [comment]
Need to rebase again :D

**Comment by cbourgois** [comment]
Close it, as it uses now feature flipping (https://github.com/ovh/manager/pull/4126)

**Pull request closed without merging**
