### PR TITLE
fix(details.service-keys): fix regenerate key module name

### PR DESCRIPTION
**Pull request by varun257**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-22065
| License          | BSD 3-Clause

## Description

fix wrong module name

### CODE REVIEW

**Review by antleblanc — DISMISSED** [review]
@varun257 Commit type is defined as a `feat` but looks like a `fix`. Isn't it?
Never mind, it could be fixed once it will be merged.

**Comment by varun257** [comment]
Oh it is fix!! ill rename the commit message

**Review by ganeshkumar1989 — APPROVED** [review]

**Review by antleblanc — APPROVED** [review]

**Review by Heiiji — APPROVED** [review]

**Review by JeremyDec — APPROVED** [review]

**Review by marie-j — APPROVED** [review]

**Review by cbourgois — APPROVED** [review]

**Comment by cbourgois** [comment]
Maybe should target `master` ?

**Review by mohammed-zahaf — APPROVED** [review]

**Comment by antleblanc** [comment]
> Maybe should target `master` ?

I agree. But we can integrate it into the upcoming release.
see#4155

**Comment by antleblanc** [comment]
Some checks are missing (Waiting for status to be reported).
Triggered a new run from our CI/CD platform.

**Pull request merged**
