### PR TITLE
feat(web.hosting): main domain

### PR DESCRIPTION
**Pull request by cbourgois**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix MANAGER-4179, MANAGER-3329
| License          | BSD 3-Clause

## Description

Remove main domain informations on hosting.

### CODE REVIEW

**Comment by antleblanc** [comment]
Hi @cbourgois!

We recently merged #1336 which apply Prettier rules so could you please rebase
your branch on `develop`?

To easily resolve conflicts you can **ignore** `HEAD` changes and only keep yours.

After that you can run:

```sh
$ yarn run lint
```

This command will lint the entire codebase.

or:

Amend your commit to trigger the `pre-commit` hook (prettier will be launched
under the hood).

Thanks!

**Comment by cbourgois** [comment]
Will be done when other required changes will be done to. If I rebased now, I should rebase again in the future. 
Waiting for other related features.

**Comment by cbourgois** [comment]
Rebased on develop

**Comment by antleblanc** [comment]
@cbourgois Could you please resolve existing conflicts?
Thank you!

**Comment by cbourgois** [comment]
Fix conflicts.

**Pull request merged**
