### PR TITLE
fix(i18n): add missing translations [CDS 1836]

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-55227
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~ (not applicable)
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ (not applicable)

### :bug: Bug Fixes

7ce116d - fix(i18n): add missing translations [CDS 1836]

Signed-off-by: CDS Translator Agent <opensource@ovh.net>

### CODE REVIEW

**Review by vks-ovh — APPROVED** [review]

**Review by anooparveti — DISMISSED** [review]

**Comment by antleblanc** [comment]
Rebasing on `develop` branch (resolving conflicts).

**Comment by antleblanc** [comment]
Rebased successfully on `develop` branch.

**Review by anooparveti — APPROVED** [review]

**Review by anooparveti — DISMISSED** [review]

**Comment by antleblanc** [comment]
Rebasing on `master` branch (resolving conflicts).

**Comment by antleblanc** [comment]
Rebased successfully.

**Review by anooparveti — DISMISSED** [review]

**Review by anooparveti — APPROVED** [review]

**Review by sachinrameshn — APPROVED** [review]

**Pull request merged**
