### PR TITLE
Lazy load telephony to optimize telecom manager bootstrap

### PR DESCRIPTION
**Pull request by cbourgois**
| Question         | Answer
| ---------------- | ---
| Branch?          | `perf/telecom`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix MANAGER-5832
| License          | BSD 3-Clause

## Description

* first commit : Split `telecom/telephony` into multiple module (using import/export) to help us to put some lazy loading to avoid to load large chunks on bootstrap

* second commit : Add lazy loading in `telephony` base states to avoid to load all telephony modules during the bootstrap of the application.

### CODE REVIEW

**Review by antleblanc — APPROVED** [review]

**Review by marie-j — APPROVED** [review]
Great job !

**Comment by ovh-cds** [comment]
CDS Report installation#16462.0 ✘  
* Stage 1
  * Install ✘

**Comment by cbourgois** [comment]
I have to update commits messages to add `ref: MANAGER-5832`

**Comment by cbourgois** [comment]
> I have to update commits messages to add `ref: MANAGER-5832`

Done.

**Pull request merged**
