### PR TITLE
Feat/manager 10109: add month word

### PR DESCRIPTION
**Pull request by mohammed-zahaf**
| Question         | Answer
| ---------------- | ---
| Branch?          | `MANAGER-10085`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-10109
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
add `month` word to inform customer that price is per month

### CODE REVIEW

**Review by sachinrameshn — APPROVED** [review]

**Comment by sachinrameshn** [comment]
> Question	Answer
> Branch?	`master`
> Bug fix?	no
> New feature?	yes
> Breaking change?	no
> Tickets	MANAGER-10109
> License	BSD 3-Clause
> * [x]  Try to keep pull requests small so they can be easily reviewed.
> * [x]  Commits are signed-off
> * [ ]  ~Only FR translations have been updated~
> * [x]  Branch is up-to-date with target branch
> * [x]  Lint has passed locally
> * [x]  Standalone app was ran and tested locally
> * [x]  Ticket reference is mentioned in linked commits (internal only)
> * [ ]  ~Breaking change is mentioned in relevant commits~
> 
> ## Description
> add `month` word to inform customer that price is per month

Can you please check Lint error. JSURL import is missing.

**Comment by sachinrameshn** [comment]
Can you check Lint error. I guess JSURL import is missing.

**Review by sachinrameshn — DISMISSED** [review]

**Review by sachinrameshn — APPROVED** [review]

**Comment by mohammed-zahaf** [comment]
> Can you check Lint error. I guess JSURL import is missing.

You have right @sachinrameshn, it works because deps has been imported globaly.
But it's more relevant to import it where we need it.

Fixed and thank

**Review by ghyenne — APPROVED** [review]

**Review by brofik — APPROVED** [review]

**Comment by mohammed-zahaf** [comment]
Global QA will be made on base branch.

**Pull request merged**
