### PR TITLE
fix: prepare new dedicated server OS usages (#4767)

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `release/2021-w16`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | PUBM-11673, DTRSD-34698
| License          | BSD 3-Clause

### :bug: Bug Fixes

fix: prepare new dedicated server OS usages (#4767)

### :house: Internal

No quality check required.

### :flags: Translations

- [x] TRANS-34363

Signed-off-by: Jean-Baptiste Delon <jean-baptiste.delon@ovhcloud.com>

cc @JayBeeDe

### CODE REVIEW

**Review by cbourgois — APPROVED** [review]

**Review by JeremyDec — DISMISSED** [review]

**Comment by JayBeeDe** [comment]
Hi,
Tell me when this is merged because I'm waiting this change to be in prod in order to start the OS usage migration.

**Comment by antleblanc** [comment]
Pulling translations.

**Comment by antleblanc** [comment]
Translations has been pulled successfully.

**Review by JeremyDec — APPROVED** [review]

**Comment by antleblanc** [comment]
Rebasing on `release/2021-w16` branch.

**Comment by antleblanc** [comment]
Rebased successfully on `release/2021-w16` branch.

**Pull request merged**
