### PR TITLE
Fix/manager 4343

### PR DESCRIPTION
**Pull request by radireddy**
The language field is disabled in signup page if the country selected is Singapure

ref: MANAGER-4343

### CODE REVIEW

**Comment by radireddy** [comment]
Regarding setting the first language, I thought about it. But, we can not do it because the field is optional and a customer can select it or ignore it.

**Comment by marie-j** [comment]
> Regarding setting the first language, I thought about it. But, we can not do it because the field is optional and a customer can select it or ignore it.

I'm having trouble understanding the need here, because the field is disabled if there is only one choice though the customer cannot select the optional field. Shouldn't it be disabled if there is no choice ?

**Comment by radireddy** [comment]
@marie-j If there are no languages and fields is disabled, it might be very confusing to the user. I think hiding the field if there are no languages makes sense. I think every country has at least one language, for Singapur it is English. But I am not very sure about this.

**Comment by antleblanc** [comment]
Rebased on following commit: a8471875e37973fd3807012229bb89345bd8224e

**Pull request merged**
