### PR TITLE
fix(server.details): fixed wrong naming case for ext3 and ext4 fs

### PR DESCRIPTION
**Pull request by JayBeeDe**
ref: MANAGER-10430

Signed-off-by: Jean-Baptiste Delon <jean-baptiste.delon@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix MANAGER-10430
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated <- No because is same content across all languages
- [x] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

See commit

### 🎏 Translations

- [x] TRANS-47775

### CODE REVIEW

**Review by anooparveti — CHANGES_REQUESTED** [review]
Could you please update only `fr_FR` files? We are not supposed to modify other translation files. The changes to other languages files must come from translation team only.
Thanks!

**Comment by JayBeeDe** [comment]
> Could you please update only `fr_FR` files? We are not supposed to modify other translation files. The changes to other languages files must come from translation team only. Thanks!

done

**Review by stif59100 — DISMISSED** [review]

**Review by anooparveti — DISMISSED** [review]

**Comment by anooparveti** [comment]
Pulling translations.

**Review by anooparveti — DISMISSED** [review]

**Review by anooparveti — APPROVED** [review]

**Review by stif59100 — APPROVED** [review]

**Comment by anooparveti** [comment]
Ignoring the `has conflicts` label as the conflicts were resolved with the rebase.

**Pull request merged**
