### PR TITLE
Fix/hub us

### PR DESCRIPTION
**Pull request by marie-j**
| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/manager-hub`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | none
| License          | BSD 3-Clause

## Description

Hide links that are not available in the US

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#10476.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#10476.1 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#10476.2 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#10476.3 ✘  
* 
  * Build ✘

**Comment by marie-j** [comment]
Fixed conflicts

**Pull request merged**
