### PR TITLE
fix(server-sidebar): restore items loading on click

### PR DESCRIPTION
**Pull request by cbourgois**
### Description of the Change

81cc265a9 — fix(server-sidebar): restore items loading on click

### CODE REVIEW

**Comment by FredericEspiau** [comment]
This is basically reversing https://github.com/ovh/manager/pull/1833, so does this mean empty sections will be kept open ? Can you take this into account maybe ?

**Comment by cbourgois** [comment]
@FredericEspiau Empty sections will be kept visible. If we want to display/hide sections at the app initialization we should retrieve all services at the bootstrap even if we don't need them.

**Comment by FredericEspiau** [comment]
@cbourgois but why did we access the original PR then ? We should wonder about this

**Comment by julieni** [comment]
> @cbourgois but why did we access the original PR then ? We should wonder about this

Hi, as the contributor of the original PR, I have to say it was a change requested by users on mailing lists, and it took some time to implement as it requested changes in submodule too.

I think the best way to go is to provide an API call to get services count by section. 1 request only, and this would also allow to display a badge with services count on every section.

**Comment by julieni** [comment]
And also, you accepted the PR because it improved UX, I think. It's not because the proper, lightweight API calls are missing that we can't improve UX.

It makes me think of https://github.com/ovh/manager/pull/1955, the API is not ready (in this case not even safe), so all improvements should go to trash ? ...

**Comment by cbourgois** [comment]
Hello @julieni,

The original feature for the sidebar was to load services only when the user click on a product section (_load only what you needs_).

I understand that the original PR improved UX for some customers who don't have all products.
They saw all the products in the sidebar and when they clicked to open a product section they saw "_No services_".

But we also have customers who have a lot of different services, and regarding the performances we don't want to make 15 requests to the API to retrieve all the products to detect if we need to show / hide them. 

I think we should restore the original feature (loading services when the user wants to see them) for now, and we will open an issue. IMO, this is the best compromise.

In this issue we should address this sidebar UX improvement for **all** customers based on your needs. 
As you said, we could have an API to get number of services to initialize the sidebar (hide/show products sections), and keep lazy-loading the services.

Thanks,

**Comment by julieni** [comment]
> I think we should restore the original feature (loading services when the user wants to see them) for now, and we will open an issue. IMO, this is the best compromise.
> In this issue we should address this sidebar UX improvement for **all** customers based on your needs.
> As you said, we could have an API to get number of services to initialize the sidebar (hide/show products sections), and keep lazy-loading the services.

I totally agree on this, but due to the lack of such an API endpoint, the only way was to preload the services list.
Please provide such an API endpoint and I'll be happy to improve my PR using it ;)

**Comment by cbourgois** [comment]
The issue is created : #2360

**Pull request merged**
