### PR TITLE
fix(billing): set split payment as standard key word

### PR DESCRIPTION
**Pull request by JeremyDec**
ref: MANAGER-7071
Signed-off-by: JeremyDec <jeremy.de-cesare@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-7071
| License          | BSD 3-Clause

### CODE REVIEW

**Review by marie-j — DISMISSED** [review]

**Review by antleblanc — APPROVED** [review]

**Review by Heiiji — DISMISSED** [review]

**Review by Heiiji — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report translator-pull#977.0 ■   
* 
  * pull ■

**Comment by ovh-cds** [comment]
CDS Report translator-pull#977.0 ■   
* 
  * pull ■

**Comment by antleblanc** [comment]
@JeremyDec Pull Request description refer to `develop` as target branch but this Pull Request is targeting `master`.
Could you please help me to find the right target branch?

Thank you!

**Comment by JeremyDec** [comment]
@antleblanc yes the branch was initially targetting `develop`, description has been updated

**Review by marie-j — APPROVED** [review]

**Pull request closed without merging**
