### PR TITLE
New release

### PR DESCRIPTION
**Pull request by antleblanc**
# 📦 New release

Approximate release date: 📆 16/11/2020

### :zap: Performances

42b1a31 - perf: remove unused ckeditor import (#3995)
81f51a5 - perf: remove unused angular-flash-alert dependency (#4012)
980de2c - perf: remove unused lodash import (#4013)

### :sparkles: Features

726835d - feat(nasha.order): improve order flow (#4001)

### :bug: Bug Fixes

- [x] DTRSD-23423 - fix(i18n): add missing translations [CDS 647] (22b29a7)
- [x] DTRSD-22242 - fix(user): change label for deactivate 2FA codes (323573a) 
- [x] DTRSD-23952 - fix(ip): not possible to add  mac address (#4003)
- [x] MANAGER-5966 - fix(vps): remove maintenance warning message (#3999)

<details>
<summary>Other bugfixes</summary><br>

ef729d5 - fix(billing): remove pagination if empty list (#3984)
</details>

### :recycle: Refactor

- [x] MANAGER-5672 - refactor(dedicated): dedicatedCloud component (#3685)

### :zap:  Performances

573e8ac - pref: remove unused intl-tel-input dependency (#3994)
42b1a31 - perf: remove unused ckeditor import (#3995)
6d5b608 - perf: lazy load angular-qr dependency (#3996)
b547a59 - perf: remove raphael and justgage unused deps (#3997)
9cf553c - perf: remove full lodash import (#4007)

### ✨ Features

22c9d30 - feat(dedicated-cloud): add survey banner (#4017)

### :sparkles: Features

- [x] MANAGER-5524 - feat(public-cloud): kubernetes anti-affinity (#3860)
- [x] MANAGER-5525 - feat(pci.kube.nodes): add monthly billing information column (#3860)

### :bug: Bug Fixes

- [x] DTRSD-8610 - fix(i18n): add missing translations [CDS 660] (c99b0b9)
- [x] DTRSD-22073 - fix(project.quota.increase-request): fix quota type id (#3824)

### :bug: Bug Fixes

- [x] DTRSD-22218 - fix(telephony.service.voicemail): replace aapi call with autocomplete (#3825)
- [x] DTRSD-23444 - fix(sms.batches.create): fix empty recipients array and slotID (#3990)
- [x] UXCT-333 - fix(pack.xdsl.access): remove disabled for ftth pack (#3914)
- [x] UXCT-342 - fix(pack.resiliation): fix on resiliation date test (#3927)

<details>
<summary>Other bugfixes</summary><br>

700dbf3 - fix(pack.xdsl.modem): disable modem wifi config if remote config is disabled (#3630)
</details>

---

### :bug: Bug Fixes

3dfc129 - fix(translations): clean translations files (#4008)

### :arrow_up: Upgrade

7dab529 - build(dev-deps): upgrade VuePress to v1.7.1 (#3950)

### :construction_worker: Build

9e718f7 - build: provide description entry into package.json file (#3950)

### :memo: Documentation

ce73135 - docs(guide): update releasing template (#3950)
a07ec59 - docs(guide): update applications list (#3950)

### :green_heart: Continuous Integration

2b4de56 - ci(workflow): add gh-pages actions (#3986)

### :zap: Performances

4691d0c - perf: remove unused angular-vs-repeat dependency (#4010)
9114662 - perf: remove unused jquery-cookie dependency (#4014)

#### :sparkles: Features

6e4135f - feat(logs): make module lazy loaded #4009 

#### :bug: Bug Fixes

558276f - fix(deps): add missing deps (#4004)

#### :bug: Bug Fixes

1c624c4 - fix(models): add dedicatedCloud class (#3685)

#### :bug: Bug Fixes

1e6d9c5 - fix(deps): add missing deps (#4004)

#### :sparkles: Features

52676e6 - feat(registry): add static sync command (#4026)

#### :bug: Bug Fixes

8637ef1 - fix(loaders): add es6 proposals for translations webpack plugins (#3816)

#### :bug: Bug Fixes

562b35c - fix(config): complete nprogress when redirect to same state (#3974)

#### :bug: Bug Fixes

cd7b610 - fix(deps): add missing deps (#4004)

#### :sparkles: Features

1c52880 - feat: prompt new question to describe application (#3950)

### :flags: Translations

- [x] TRANS-29355

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report translator-pull#649.0 ✘  
* 
  * pull ✘

**Comment by ovh-cds** [comment]
CDS Report build#16913.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build#16929.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report test#16929.0 ✘  
* Stage 1
  * lint ✔ 
  * SemVer ✘

**Comment by ovh-cds** [comment]
CDS Report build#16985.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report test#16985.0 ✘  
* Stage 1
  * lint ✔ 
  * SemVer ✘

**Comment by ovh-cds** [comment]
CDS Report test#17014.0 ✘  
* Stage 1
  * lint ✔ 
  * SemVer ✘

**Review by cbourgois — APPROVED** [review]

**Pull request merged**
