### PR TITLE
fix(hosting.dashboard): update recommended version for `php`

### PR DESCRIPTION
**Pull request by TheGoat-ma**
| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets           | MANAGER-8768
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

Php7.3 is EOL, we should advise our customer to use a Major version with the right container

### :flags: Translations

- [x] TRANS-41726

### CODE REVIEW

**Review by antleblanc — CHANGES_REQUESTED** [review]
Changes looks good to me.
Before merging it, could you please rebase it on `master` branch?
Thank you!

**Comment by TheGoat-ma** [comment]
@antleblanc  done and thanks for the review

**Review by antleblanc — DISMISSED** [review]

**Review by Jisay — DISMISSED** [review]

**Comment by antleblanc** [comment]
Pulling translations.

**Comment by antleblanc** [comment]
Rebasing on `develop` in order to solve existing conflict.
```txt
 packages/manager/apps/web/client/app/hosting/dashboard/translations/Messages_pl_PL.json 
```

**Pull request merged**
