### PR TITLE
Sync develop & master

### PR DESCRIPTION
**Pull request by ovh-ux-cds**
Automerge master in develop

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report translations-cleaner#7.0 ✘  
* Stage 1
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report translations-cleaner#8.0 ✘  
* Stage 1
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report translations-cleaner#9.0 ✘  
* 
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report translations-cleaner#10.0 ✘  
* 
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report translations-cleaner#11.0 ✘  
* 
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report translations-cleaner#12.0 ✘  
* 
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report translations-cleaner#13.0 ✘  
* 
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report translations-cleaner#14.0 ✘  
* 
  * New Job ✘

**Comment by antleblanc** [comment]
Automerge master in develop has failed due to conflict. I close this pull request and fix conflict manually.

Thanks!

**Pull request merged**
