### PR TITLE
Import @ovh-ux/ng-ovh-checkbox-table

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-4502
| License          | BSD 3-Clause

## Description

Import **@ovh-ux/ng-ovh-checkbox-table** :truck:

Using following command:

```sh
lerna import ~/Code/github/ovh-ux/ng-ovh-checkbox-table \
  --dest=packages/components \
  --preserve-commit
```

### :construction_worker_man: Build

7772625 - build: remove extra parts

### :memo: Documentation

fa98a8b - docs: update README.md file

### :bookmark: TODOs

- [x] Update CONTRIBUTORS file.

### CODE REVIEW

**Comment by antleblanc** [comment]
`yarn.lock` conflict solved via the following commit: 23f0a0e

**Comment by ovh-cds** [comment]
CDS Report installation#10606.0 ✘  
* Stage 1
  * Install ✘

**Comment by ovh-cds** [comment]
CDS Report installation#10606.0 ✘  
* Stage 1
  * Install ✘

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#10607.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#10607.0 ✘  
* 
  * Build ✘

**Pull request merged**
