### PR TITLE
feat(telephony.alias): add intermediate state

### PR DESCRIPTION
**Pull request by marie-j**
| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/solarsteein-telecom`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#15912.0 ✘  
* 
  * Build ✘

**Comment by antleblanc** [comment]
Hi @marie-j!

FYI, since #3859 has been merged, there are now some conflicts.

Could you please have a look when you'll have time?
Thank you!

**Comment by ovh-cds** [comment]
CDS Report test#16856.0 ✘  
* Stage 1
  * lint ✘  
  * SemVer ✔

**Comment by marie-j** [comment]
@antleblanc conflicts have been solved, 
thanks

**Review by JeremyDec — APPROVED** [review]

**Pull request merged**
