### PR TITLE
perf: remove raphael and justgage unused deps

### PR DESCRIPTION
**Pull request by frenautvh**
| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | 
| License          | BSD 3-Clause

## Description

remove unused dependencies raphael & justgage from dedicated

### CODE REVIEW

**Review by antleblanc — DISMISSED** [review]

**Review by antleblanc — DISMISSED** [review]

**Comment by antleblanc** [comment]
Conflict in `yarn.lock` file.
I'm rebasing this branch on `develop`.

**Comment by antleblanc** [comment]
Rebased successfully on `develop` branch.

**Review by antleblanc — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report test#16981.0 ✘  
* Stage 1
  * lint ✔ 
  * SemVer ✘

**Comment by ovh-cds** [comment]
CDS Report test#16981.1 ✘  
* Stage 1
  * lint ✔ 
  * SemVer ✘

**Comment by ovh-cds** [comment]
CDS Report test#16981.2 ✘  
* Stage 1
  * lint ✔ 
  * SemVer ✘

**Comment by ovh-cds** [comment]
CDS Report test#17009.0 ✘  
* Stage 1
  * lint ✔ 
  * SemVer ✘

**Pull request merged**
