### PR TITLE
docs: add example

### PR DESCRIPTION
**Pull request by antleblanc**
## :memo: Documentation

f9f81f4 - docs: add example

## :house: Internal

No quality check required.

Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#9543.0 ✘  
* 
  * Build ✘

**Comment by marie-j** [comment]
Maybe you could scope the commit to the impacted package ?

**Comment by antleblanc** [comment]
> Maybe you could scope the commit to the impacted package ?

You mean:
```txt
docs(example): ...
```

or

```txt
docs(ng-ui-router-title): ...
```

Let's say we will introduce a bug fix to the provider or the directive, it will make sense to specify the scope but not in this example I would say.

I mean:
```txt
fix(provider): ...
```

**Comment by marie-j** [comment]
> > Maybe you could scope the commit to the impacted package ?
> 
> You mean:
> 
> ```
> docs(example): ...
> ```
> 
> or
> 
> ```
> docs(ng-ui-router-title): ...
> ```
> 
> ?
> 
> Let's say we will introduce a bug fix to the provider or the directive, it will make sense to specify the scope but not in this example I would say.
> 
> I mean:
> 
> ```
> fix(provider): ...
> ```

@antleblanc as seen together it doesn't make sense to scope :)

**Pull request merged**
