### PR TITLE
refactor(link): use buildURL instead of redirectionService

### PR DESCRIPTION
**Pull request by cbourgois**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix 
| License          | BSD 3-Clause

## Description

Use `buildURL` from `@ovh-ux/ufrontend/url-builder` instead of `RedirectionService`.

`RedirectionService` store URL hash behind identifier (`autorenew`, `contactManagement`...) but URL hash are already identifiers.

I keep `RedirectionService` for now for external URLs (guides/help/tasks).

### CODE REVIEW

**Review by frenautvh — APPROVED** [review]

**Comment by cbourgois** [comment]
I marked it as`blocked`.
IMHO we should review and merge https://github.com/ovh/manager/pull/4184 before rebasing this one and avoid to build hash manually :

```js
this.orderTrackingLink = buildURL(
  'dedicated',
  `#/billing/order/${encodeURIComponent(this.order.orderId)}`,
);
```

Should be : 

```js
this.orderTrackingLink = buildURL(
  'dedicated',
  `#/billing/order/:orderId`,
  { orderId: this.order.orderId },
);
```

**Comment by cbourgois** [comment]
Rebased on `develop` to use `url-builder` pattern replacement (https://github.com/ovh/manager/pull/4184)

**Comment by antleblanc** [comment]
@cbourgois There are some conflicts :see_no_evil:!

**Comment by cbourgois** [comment]
> @cbourgois There are some conflicts 🙈!

Rebased on `develop`

**Comment by cbourgois** [comment]
Rebased on `develop` (fix conflict on metrics)

**Review by antleblanc — APPROVED** [review]

**Pull request merged**
