### PR TITLE
fix: redeploy cluster initial config

### PR DESCRIPTION
**Pull request by anooparveti**
| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/nutanix-redeploy`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-8615
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~ [n/a]
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ [n/a]

## Description

 Fix for redeploying the nutanix cluster initial config

### CODE REVIEW

**Review by antleblanc — CHANGES_REQUESTED** [review]
Some checks were not successful
> CDS/UXMAN-manager-test-v3 — test-v3: Fail

**Comment by anooparveti** [comment]
> Some checks were not successful
> 
> > CDS/UXMAN-manager-test-v3 — test-v3: Fail

Hello @antleblanc,
The fix is targeting another intermediate branch `feat/nutanix-redeploy`. The above said check is failing because of the change in the dependency version. This will be handled while merging the base branch.

**Review by mohammed-zahaf — APPROVED** [review]

**Review by Jisay — APPROVED** [review]

**Review by antleblanc — CHANGES_REQUESTED** [review]
To solve the following issue:
> CDS/UXMAN-manager-test-v3 — test-v3: Fail

The intermediate branch `feat/nutanix-redeploy` needs to be updated first.
In that way it will fix the original issue. Once it's done, then you can rebase
this branch `fix/MANAGER-8615` against `feat/nutanix-redeploy`.

As a result, both branches will have successful checks (required for merging them).

**Review by varun257 — APPROVED** [review]

**Comment by radireddy** [comment]
> To solve the following issue:
> 
> > CDS/UXMAN-manager-test-v3 — test-v3: Fail
> 
> The intermediate branch `feat/nutanix-redeploy` needs to be updated first. In that way it will fix the original issue. Once it's done, then you can rebase this branch `fix/MANAGER-8615` against `feat/nutanix-redeploy`.
> 
> As a result, both branches will have successful checks (required for merging them).

As discussed we will take care this issue in the base branch. This issue is happening more frequently and as a result we have to do lot repetitive work. We will consider this use case an exception and take care of the issue in the base branch. This will allow us to move fast in QA, translation etc.

**Review by radireddy — APPROVED** [review]

**Pull request merged**
