### PR TITLE
Build/angular deps

### PR DESCRIPTION
**Pull request by cbourgois**
| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix DTCORE-38
| License          | BSD 3-Clause

## Description

Bump `angular` & `angular-translate` to latests versions.
I use fixed version for `angular,` as [it is deprecated ](https://www.npmjs.com/package/angular).

### CODE REVIEW

**Comment by cbourgois** [comment]
Rebased on `master`

**Review by frenautvh — DISMISSED** [review]

**Comment by antleblanc** [comment]
Relates to #7615

**Review by antleblanc — APPROVED** [review]

**Comment by antleblanc** [comment]
**thought(non-blocking):** sao packages could also received this update.

**Review by JeremyDec — APPROVED** [review]

**Review by Jisay — APPROVED** [review]

**Review by antleblanc — DISMISSED** [review]

**Comment by cbourgois** [comment]
Rebased on `master`

**Review by antleblanc — APPROVED** [review]

**Review by sachinrameshn — APPROVED** [review]

**Pull request closed without merging**
