### PR TITLE
Fix/hosting/upgrade/contracts

### PR DESCRIPTION
**Pull request by FredericEspiau**
MANAGER-4488

# Validation
This has already been validated by three of my peers, but I've rebased in the meanwhile

### CODE REVIEW

**Comment by FredericEspiau** [comment]
@antleblanc no it's not related to a ticket, I haven't have the time to create it yet :)

**Comment by FredericEspiau** [comment]
@antleblanc I've added the ticket now that's it's created :)

**Comment by FredericEspiau** [comment]
@antleblanc  `--verbose` ? 🙂 

I had to search to know what you were talking about

**Comment by antleblanc** [comment]
> @antleblanc `--verbose` ? 
> 
> I had to search to know what you were talking about

Sorry it's a shortcut to a popular command named [`sed`](https://www.gnu.org/software/sed/manual/sed.html) that perform basic text transformation :)

I was mentioning that you can replace the text `componant` (typo) into `component` from your commit message.

**Comment by FredericEspiau** [comment]
@antleblanc done !

**Pull request merged**
