### PR TITLE
feat(module.server-sidebar): hide empty sections

### PR DESCRIPTION
**Pull request by julieni**
Signed-off-by: Julien Issler <julien@issler.net>

Needs module update: https://github.com/ovh-ux/ng-ovh-sidebar-menu/pull/111

### CODE REVIEW

**Comment by antleblanc** [comment]
Thanks @julieni for you contribution.

Please refer to my comment: https://github.com/ovh-ux/ng-ovh-sidebar-menu/pull/107#issuecomment-558037841

**Comment by julieni** [comment]
@antleblanc in fact this PR is for the web universe at first, for example hiding "email pro" or "microsoft > office" if no products are present in these categories

**Comment by antleblanc** [comment]
Hi @julieni!

We recently merged #1336 which apply Prettier rules so could you please rebase
your branch on `develop`?

To easily resolve conflicts you can **ignore** `HEAD` changes and only keep yours.

After that you can run:

```sh
$ yarn run lint
```

This command will lint the entire codebase.

or:

Amend your commit to trigger the `pre-commit` hook (prettier will be launched
under the hood).

Thanks!

**Comment by julieni** [comment]
Hum, it seems something went wrong when trying to rebase/merge...

**Comment by julieni** [comment]
> Hum, it seems something went wrong when trying to rebase/merge...

Ok, now fixed

**Pull request merged**
