### PR TITLE
Import @ovh-ux/ng-ovh-form-flat

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-4508
| License          | BSD 3-Clause

## Description

Import **@ovh-ux/ng-ovh-form-flat** :truck:

Using following command:

```sh
lerna import ~/Code/github/ovh-ux/ng-ovh-form-flat \
  --dest=packages/components \
  --preserve-commit
```

### :construction_worker_man: Build

5cc18f8 - build: remove extra parts

### :memo: Documentation

cc16cf0 - docs: update README.md file

### 🔖 TODOs

- [x] Update CONTRIBUTORS file.

### CODE REVIEW

**Comment by antleblanc** [comment]
`yarn.lock` conflict solved via the following commit: f5f411a

**Comment by ovh-cds** [comment]
CDS Report installation#10588.0 ✘  
* Stage 1
  * Install ✘

**Comment by ovh-cds** [comment]
CDS Report installation#10588.0 ✘  
* Stage 1
  * Install ✘

**Comment by ovh-cds** [comment]
CDS Report installation#10588.1 ✘  
* Stage 1
  * Install ✘

**Comment by ovh-cds** [comment]
CDS Report installation#10588.1 ✘  
* Stage 1
  * Install ✘

**Pull request merged**
