### PR TITLE
Feat/miaw/sqlperso

### PR DESCRIPTION
**Pull request by JeremyDec**
| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | yes
| New feature?     | yes
| Breaking change? | yes
| Tickets          | MANAGER-4022
| License          | BSD 3-Clause

## Description

Re-open of https://github.com/ovh/manager/pull/2920

Additional commit => 3c6d11d

## Related 

- [x] TRANS-26104

### CODE REVIEW

**Comment by FredericEspiau** [comment]
Incredible code 👍

**Comment by JeremyDec** [comment]
Thanks, for once, I've decided to make a good one :)

**Comment by ovh-cds** [comment]
CDS Report test-manager_2#13275.0 ✘  
* Stage 1
  * e2e -   
  * lint ✔ 
  * SemVer ✘

**Comment by ovh-cds** [comment]
CDS Report test-manager_2#13281.0 ✘  
* Stage 1
  * e2e -   
  * lint ✔ 
  * SemVer ✘

**Comment by ovh-cds** [comment]
CDS Report test-manager_2#13286.0 ✘  
* Stage 1
  * e2e -   
  * lint ✔ 
  * SemVer ✘

**Pull request merged**
