### PR TITLE
style: apply eslint config rules

### PR DESCRIPTION
**Pull request by antleblanc**
# Apply ESLint config rules

## :lipstick: Style

7510529 - style: apply eslint config rules

most of manual fixes relates to:
- max-len
- no-mixed-operators
- no-redeclare

## :link: Related

- #1944

## :house: Internal

- No quality check required.

Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report installation#7993.0 ✘  
* Stage 1
  * Install ✘

**Comment by FredericEspiau** [comment]
Next time, it would be cool to differenciate between automated fixes (i.e. fixes I won't look at), and manual fixes (i.e. those I will look at) 😅

**Comment by antleblanc** [comment]
> Next time, it would be cool to differenciate between automated fixes (i.e. fixes I won't look at), and manual fixes (i.e. those I will look at)

You're right! I will apply your suggestions for upcoming similar changes.
Thanks!

**Comment by ovh-cds** [comment]
CDS Report installation#8147.0 ✘  
* Stage 1
  * Install ✘

**Pull request merged**
