### PR TITLE
Sync develop & master

### PR DESCRIPTION
**Pull request by ovh-ux-cds**
Automerge master in develop

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.0 ✘  
* Stage 1
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.1 ■   
* Stage 1
  * New Job ■

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.1 ■   
* Stage 1
  * New Job ■

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.4 ✘  
* Stage 1
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.6 ✘  
* Stage 1
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.7 ■   
* Stage 1
  * New Job ■

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.7 ■   
* Stage 1
  * New Job ■

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.9 ■   
* Stage 1
  * New Job ■

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.9 ■   
* Stage 1
  * New Job ■

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.13 ■   
* Stage 1
  * New Job ■

**Comment by ovh-cds** [comment]
CDS Report manager-build-time-to-graphite#1.13 ■   
* Stage 1
  * New Job ■

**Comment by antleblanc** [comment]
Automerge master in develop has failed due to conflict. We close this pull request and fix conflict manually.

Thanks!

**Pull request closed without merging**
