### PR TITLE
feat(ng-ovh-contact): replace lodash with lodash-es

### PR DESCRIPTION
**Pull request by frenautvh**
| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | 
| License          | BSD 3-Clause

## Description

Replace lodash with lodash-es in order to reduce bundle size

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#12511.0 ✘  
* 
  * Build ✘

**Comment by ovh-cds** [comment]
CDS Report build#12511.1 ✘  
* 
  * Build ✘

**Comment by antleblanc** [comment]
@frenautvh Regarding the changes (and the label chosen) do you think it could deserve a commit type [`perf`](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type) instead?.

**Comment by ovh-cds** [comment]
CDS Report build#12524.0 ✘  
* 
  * Build ✘

**Comment by antleblanc** [comment]
@frenautvh Could you please resolve existing conflict in order to be able to merge it?

Also make sure that the following check `CDS/UXMAN-manager-build` passed:)

**Pull request merged**
