### PR TITLE
fix(payment.method.add): fix sepa direct help links

### PR DESCRIPTION
**Pull request by radireddy**
the language of sepa direct help links must be same as that of subsidiary

ref: DTRSD-68625

Signed-off-by: Ravindra Adireddy <ravindra.adireddy@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-68625
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

### CODE REVIEW

**Review by antleblanc — DISMISSED** [review]

**Review by Jisay — APPROVED** [review]

**Review by JeremyDec — APPROVED** [review]

**Review by JeremyDec — CHANGES_REQUESTED** [review]
Hello @radireddy, it seems that the check "Run tests BDD" has failed, you might need to rebase your branch

**Comment by radireddy** [comment]
> Hello @radireddy, it seems that the check "Run tests BDD" has failed, you might need to rebase your branch

done, thanks

**Comment by antleblanc** [comment]
@radireddy Can you please rebase it on `master` branch? Thanks!

**Comment by radireddy** [comment]
> 

@antleblanc I am getting conflicts on files that I have not made any changes while rebasing with master. Any issues in master?

**Comment by radireddy** [comment]
> > 
> 
> @antleblanc I am getting conflicts on files that I have not made any changes while rebasing with master. Any issues in master?

its done now

**Review by antleblanc — APPROVED** [review]

**Pull request merged**
