### PR TITLE
New release

### PR DESCRIPTION
**Pull request by antleblanc**
# 📦 New release

Approximate release date: 📆 13/01/2021

### :sparkles: Features

- [x] MANAGER-6079 - feat(hosting.user-logs): revamp statistics display (#4208)

### :bug: Bug Fixes

- [x] MANAGER-6017 - feat(hosting.multisite): enforce ipv6 configuration for webhosting (#4106)
- [x] DTRSD-25612 - fix(hosting.email.activate): remove typo (#4242)

### :sparkles: Features

- [x] MANAGER-4014 - feat: add @ovh-ux/manager-cda to dedicated (#2616)

### :bug: Bug Fixes

- [x] MANAGER-5965 - fix: add error page for expired services (#4169)
- [x] MANAGER-6173 - fix(backup): fix handle when backup is doing (#4236)
- [x] MANAGER-6195 - fix(logs.detail.streams.home): improve space used column (#4243)
- [x] DTRSD-25840 - fix(ldp): update wording in order section (#4237) 

### :flags: Translations

- [x] DTRSD-22949
- [x] DTRSD-24315

### :bug: Bug Fixes

- [x] MANAGER-5490 - fix(dedicatedcloud.datacenter.drp): fix zerto plancode (#4141)

### :sparkles: Features

- [x] MANAGER-6080 - feat(instance): add start and stop instance feature (#4185)

### :bug: Bug Fixes

04b66a8 - fix(components.project.instance): fix connectionInfos typo (#4203)

### :sparkles: Features

- [x] UXCT-299 - feat(pack.migration): add contact phone on resume view for migration (#4072)

<details>
<summary>Other features</summary><br>

 559b34b - feat(telephony.service.contact): autofill urban district if required 
</details>

### :bug: Bug Fixes

- [x] DTRSD-26471 - fix(telephony.service.contact): fix postal code check for district input (#4202)
- [x] DTRSD-25113 - fix(telephony.alias.lines.add): cancel now clean all inputs (#4239)
- [x] UXCT-364 - fix(pack.migration): initialize selected building first (#4253)

### :flags: Translations

- [x] DTRSD-16690
- [x] DTRSD-25303

--- 

#### :boom: Breaking changes

90d2bc1 - feat: init @ovh-ux/manager-cda-app application (#2616)

#### :boom: Breaking changes

9ae89ec - fix(urls): remove core constant URLs (#4181)

#### :sparkles: Features

- [x] MANAGER-6081 - feat: allow to rewrite path and headers when using dev proxy (#4200)

#### :boom: Breaking changes

- [x] MANAGER-4012 - init `@ovh-ux/manager-metrics-app` application (#2686)

#### :bug: Bug Fixes

- [x] DTRSD-24835 - fix(summary): update contract label (#4217)

#### :sparkles: Features

- [x] MANAGER-5023 - feat(provider): add ovhSubsidiary param in logout url (#4143)

### :sparkles: Features

- [x] MANAGER-6021 - feat(chatbot): use feature flipping to enable chatbot (#4126)

### :rocket: 2API Endpoints

- [ ] service#42 (CDA)
- [ ] service#46 (Metrics)

### :flags: Translations

- [ ] TRANS-31252 

---

### :handshake: Contributors

@Alkorin @pdepaepe

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report translator-push#13477.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translator-push#13483.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translator-push#13485.0 ✘  
* 
  * push ✘

**Comment by ovh-cds** [comment]
CDS Report translator-push#13728.0 ✘  
* 
  * push ✘

**Review by Jisay — APPROVED** [review]

**Pull request merged**
