### PR TITLE
Feat/sms spain

### PR DESCRIPTION
**Pull request by marie-j**
ref: MANAGER-4073

### CODE REVIEW

**Comment by FredericEspiau** [comment]
Are you sure there is not at some place an address or a phone number format to change ?

**Comment by marie-j** [comment]
Translations are here : https://github.com/ovh/manager/pull/1923

**Comment by antleblanc** [comment]
> Are you sure there is not at some place an address or a phone number format to change ?

We didn't identify any places within the SMS module.

**Comment by ovh-cds** [comment]
CDS Report installation#8055.0 ■   
* Stage 1
  * Install ■

**Pull request merged**
