### PR TITLE
Upgrade both ESLint and Prettier

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | no
| License          | BSD 3-Clause

### :bug: Bug Fixes

30dd0a2 - fix(peer-deps): add missing peer deps

### :arrow_up: Upgrade

4ae57a0 - build: bump both prettier and eslint configuration

### :construction_worker: Build

d7c1cb6 - build: remove extra eslint configuration

### :lipstick: Style

1d022ce - style: apply prettier rules
344d2c0 - style: apply prettier rules

### CODE REVIEW

**Comment by frenautvh** [comment]
i'm afraid it'll make some PRs nearly impossible to rebase (solarstein for example) and think it should be done later

**Review by marie-j — APPROVED** [review]

**Comment by antleblanc** [comment]
> i'm afraid it'll make some PRs nearly impossible to rebase (solarstein for example) and think it should be done later

According to the following commit `5d8da7456e18a30f4d5d624aa285656f4a4776de` where I ran the given command:
```sh
$ yarn run format:js
```

I can exclude some workspaces (if needed) like:
- `packages/manager/apps`
- `packages/manager/modules`

**OR** second option could be to consider relying on a rebase to ease the process.

```sh
$ git rebase -Xours develop
$ ./node_modules/.bin/eslint --quiet --format=pretty "packages/manager/{apps|modules}/YOUR_FOLDER"
```

Please let me know what's your feeling about it @frenautvh.
Thank you!

**Review by Jisay — APPROVED** [review]

**Comment by antleblanc** [comment]
ping @frenautvh

**Comment by frenautvh** [comment]
> ping @frenautvh

i'm not sure we could rebase https://github.com/ovh/manager/pull/3780 easily if we merge this PR (because of moved files for example)

**Comment by antleblanc** [comment]
@frenautvh Do you want me to exclude a given list of applications/modules in order to apply latest ESLint rules?

According to the Pull Request you mentioned, here is the impacted applications/modules:
```sh
$ git diff origin/refactor/list-layout...origin/feat/solarsteein-dedicated --name-only -- 'packages/manager/apps/**.*.js' | cut -d "/" -f 4 | uniq
cloud-connect
cloud
dedicated
enterprise-cloud-database

$ git diff origin/refactor/list-layout...origin/feat/solarsteein-dedicated --name-only -- 'packages/manager/modules/**.*.js' | cut -d "/" -f 4 | uniq
cloud-connect
core
enterprise-cloud-database
iplb
nasha
server-sidebar
veeam-cloud-connect
veeam-enterprise
vps
vrack
```

Otherwise alternative that can be considered, thanks to `git mv && git rebase -Xours`, we can easily rebase on `develop` no matter changes brought by this Pull Request.

Please let me know which solutions you prefer or if you want to submit a new one, don't hesitate.

Thank you.

**Comment by antleblanc** [comment]
Rebased on `develop` to fix conflicts.

**Review by cbourgois — APPROVED** [review]

**Comment by antleblanc** [comment]
As _Solarsteein_ is making good progress, I will reschedule this changes once all
pending Pull Request will be merged.

Here is the list of pending Pull Requests:
- Telecom (OK) (#3778);
- Web Cloud (OK) (#3779);
- Bare Metal Cloud (DOING) (#3780);

/cc @frenautvh @marie-j

**Pull request closed without merging**
