### PR TITLE
Rollup configuration - Update languages list

### PR DESCRIPTION
**Pull request by antleblanc**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | yes
| Tickets          | none
| License          | BSD 3-Clause

### :boom: Breaking Changes

e4853e2 - refactor(plugins): remove both cs_CZ and lt_LT from languages list

### :arrow_up: Upgrade

4f458d4 - fix(deps): upgrade @ovh-ux/component-rollup-config to v10.0.0

### :house: Internal

No quality check required.

### CODE REVIEW

**Review by Jisay — APPROVED** [review]

**Review by marie-j — DISMISSED** [review]

**Comment by antleblanc** [comment]
Rebasing on `develop` due to a conflict on ` packages/manager/tools/component-rollup-config/src/plugins/translation-utils.ts`.

**Comment by antleblanc** [comment]
Rebased successfully on `develop` branch.

**Review by marie-j — DISMISSED** [review]

**Comment by antleblanc** [comment]
Rebasing on `develop` branch due to a conflict on following file `packages/manager/tools/webpack-config/package.json`.

**Comment by antleblanc** [comment]
Rebased successfully on `develop` branch.

**Review by marie-j — APPROVED** [review]

**Pull request merged**
